name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create config files
      run: |
        for FILE in configs/*.yaml.example; do mv $FILE "$(echo $FILE | cut -f 1 -d '.').yaml"; done

    - name: Update metadata
      run: |
        ./metadata.sh

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -covermode=count -coverpkg=./... -coverprofile=cover.out ./...
